apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  #namespace: vol-test
  namespace: rook-ceph-external
  labels:
    app: nginx
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi