apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  namespace: vol-test
  labels:
    app: nginx
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi