apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "vol-test"
  name: nginx-deployment
  labels: 
    environment : "dev"
    publish : "80"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: "vol-test"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
      - name: minecraft
        image: parzivalspace/papermc:1.20.4
