# 参考: https://dev.to/hkhelil/using-nginx-ingress-controller-and-cert-manager-for-https-with-lets-encrypt-2flh
# 参考: https://zenn.dev/masaaania/articles/e54119948bbaa2
# 公式: https://cert-manager.io/docs/tutorials/acme/http-validation/
# mk8s公式: https://microk8s.io/docs/addon-cert-manager
# mk8s公式が正直一番わかりやすかった
apiVersion: cert-manager.io/v1
# https://cert-manager.io/docs/concepts/issuer/
# Clusterにすることで、namespaceまたげる
kind: Issuer
metadata:
   name: lets-encrypt
   namespace: hello-kube-01
spec:
   acme:
      email: tamkame123@outlook.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
         # Secret resource that will be used to store the account's private key.
         name: lets-encrypt-priviate-key
      # Add a single challenge solver, HTTP01 using nginx
      solvers:
      # http認証する際に使うingress
      # - http01:
      #    ingress:
      #       class: public
      # 結局LBとか挟むとめんどそうなのでやめた
      # 参考: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
      - dns01:
         cloudflare:
            apiTokenSecretRef:
               name: cloudflare-api-token-secret
               key: api-token
