apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  namespace: hello-kube-01
spec:
  storageClassName: k8s-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi