apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  namespace: hello-kube-01
  labels:
    app: nginx
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi